@startuml

entity Utopify
entity Player
entity Deck
entity Hand
entity Card
entity character
entity terrain
entity Trait
entity Board
entity Square
entity Connection
entity Green
entity Gray
entity Red
entity Happiness
entity Score
entity Milestone

Utopify *--> Player
Player *--> Deck
Player *--> Hand
Hand --> Deck
Hand o--> "*" Card
Deck o--> "*" Card
Card o--> "1..3" Trait
Card <|-- character
Card <|-- terrain

Utopify *--> Board
Board o--> "*" Square
Board o--> "*" Connection
Square o--> "0..1" Card
Connection *--> "2" Square
Connection *--> Happiness
Connection <|-- Green
Connection <|-- Gray
Connection <|-- Red
 
@enduml